type SupportedCopyLocale = 'ru' | 'en';

const COPY = {
  ru: {
    title: 'Предложения тренера',
    subtitle: 'Просмотрите изменения перед отдельным решением применить или отклонить их.',
    refresh: 'Обновить',
    loading: 'Загрузка предложений…',
    empty: 'Предложений пока нет.',
    unavailable: 'Не удалось загрузить предложения.',
    humanTrainer: 'Тренер',
    status: 'Статус',
    statuses: {
      pending: 'Ожидает решения',
      withdrawn: 'Отозвано',
      applied: 'Применено',
      rejected: 'Отклонено',
    },
    targetState: 'Состояние шаблона',
    targetStates: {
      current: 'Актуален',
      stale: 'Шаблон изменился после предложения',
      unavailable: 'Шаблон больше недоступен',
    },
    createdAt: 'Создано',
    resolvedAt: 'Решение принято',
    targetRevision: 'Версия',
    appliedRevision: 'Применённая версия',
    message: 'Комментарий тренера',
    changes: 'Предлагаемые изменения',
    before: 'Сейчас',
    after: 'Предлагается',
    fields: {
      name: 'Название',
      goal: 'Цель',
      difficulty: 'Сложность',
      durationWeeks: 'Недель',
      cadencePerWeek: 'Тренировок в неделю',
    },
    noApply:
      'Тренер не может менять тренировку напрямую. Только клиент отдельно применяет или отклоняет ожидающее предложение.',
    apply: 'Применить изменения',
    reject: 'Отклонить предложение',
    applyFailed:
      'Не удалось применить предложение. Обновите список: доступ или версия шаблона могли измениться.',
    rejectFailed:
      'Не удалось отклонить предложение. Обновите список и проверьте актуальный статус.',
    staleApplyBlocked:
      'Применение отключено: версия шаблона уже изменилась. Предложение можно только отклонить.',
    appliedHint: 'Изменения применены после явного решения клиента.',
    rejectedHint: 'Предложение отклонено клиентом и больше не может быть применено.',
    withdrawnHint: 'Отозванное предложение нельзя применить.',
    staleHint: 'Предпросмотр сохранён, но исходный шаблон уже изменился.',
    withdraw: 'Отозвать предложение',
    withdrawFailed: 'Не удалось отозвать предложение.',
    authoringTitle: 'Создать предложение',
    authoringHint:
      'Сначала явно загрузите разрешённые шаблоны, затем выберите один. Загрузка не выполняется автоматически.',
    scopeRequired: 'Для предложений нужен доступ к шаблонам тренировок.',
    loadTemplates: 'Загрузить шаблоны',
    templatesLoading: 'Загрузка шаблонов…',
    templatesFailed: 'Не удалось загрузить шаблоны.',
    templatesEmpty: 'Доступных шаблонов нет.',
    choose: 'Выбрать',
    selected: 'Выбранный шаблон',
    nameLabel: 'Название',
    goalLabel: 'Цель',
    difficultyLabel: 'Сложность',
    durationLabel: 'Длительность, недель',
    cadenceLabel: 'Тренировок в неделю',
    noteLabel: 'Комментарий',
    notePlaceholder: 'Коротко объясните, почему предлагаете изменение',
    submit: 'Отправить предложение',
    reset: 'Сбросить',
    invalidForm: 'Измените хотя бы одно допустимое поле.',
    submitFailed: 'Не удалось создать предложение.',
  },
  en: {
    title: 'Trainer proposals',
    subtitle: 'Review changes before separately choosing to apply or reject them.',
    refresh: 'Refresh',
    loading: 'Loading proposals…',
    empty: 'No proposals yet.',
    unavailable: 'Proposals are unavailable.',
    humanTrainer: 'Trainer',
    status: 'Status',
    statuses: {
      pending: 'Awaiting decision',
      withdrawn: 'Withdrawn',
      applied: 'Applied',
      rejected: 'Rejected',
    },
    targetState: 'Template state',
    targetStates: {
      current: 'Current',
      stale: 'Template changed after proposal',
      unavailable: 'Template is no longer available',
    },
    createdAt: 'Created',
    resolvedAt: 'Decision made',
    targetRevision: 'Revision',
    appliedRevision: 'Applied revision',
    message: 'Trainer note',
    changes: 'Suggested changes',
    before: 'Current',
    after: 'Suggested',
    fields: {
      name: 'Name',
      goal: 'Goal',
      difficulty: 'Difficulty',
      durationWeeks: 'Weeks',
      cadencePerWeek: 'Sessions per week',
    },
    noApply:
      'The trainer cannot mutate workouts directly. Only the client can separately apply or reject a pending proposal.',
    apply: 'Apply changes',
    reject: 'Reject proposal',
    applyFailed:
      'Could not apply the proposal. Refresh the list because access or the template revision may have changed.',
    rejectFailed:
      'Could not reject the proposal. Refresh the list and check its current status.',
    staleApplyBlocked:
      'Apply is disabled because the template revision changed. The proposal can only be rejected.',
    appliedHint: 'Changes were applied after an explicit client decision.',
    rejectedHint: 'The client rejected this proposal and it can no longer be applied.',
    withdrawnHint: 'A withdrawn proposal cannot be applied.',
    staleHint: 'The preview is preserved, but the source template has changed.',
    withdraw: 'Withdraw proposal',
    withdrawFailed: 'Could not withdraw the proposal.',
    authoringTitle: 'Create proposal',
    authoringHint:
      'Explicitly load the allowed templates first, then choose one. Private template evidence is not loaded automatically.',
    scopeRequired: 'Workout-template access is required to create proposals.',
    loadTemplates: 'Load templates',
    templatesLoading: 'Loading templates…',
    templatesFailed: 'Could not load templates.',
    templatesEmpty: 'No templates are available.',
    choose: 'Choose',
    selected: 'Selected template',
    nameLabel: 'Name',
    goalLabel: 'Goal',
    difficultyLabel: 'Difficulty',
    durationLabel: 'Duration, weeks',
    cadenceLabel: 'Sessions per week',
    noteLabel: 'Note',
    notePlaceholder: 'Briefly explain why you suggest this change',
    submit: 'Send proposal',
    reset: 'Reset',
    invalidForm: 'Change at least one allowed field.',
    submitFailed: 'Could not create the proposal.',
  },
} as const;

const resolveLocale = (locale: string): SupportedCopyLocale =>
  locale.toLowerCase().startsWith('ru') ? 'ru' : 'en';

export const getTrainerCollaborationC4Copy = (locale: string) => COPY[resolveLocale(locale)];
