import type { SupportedLocale } from '@/localization/messages';

const copy = {
  en: {
    body: 'Body',
    strengthTraining: 'Strength & Training',
    activity: 'Activity',
    activityDetails: 'Activity details',
    highlights: 'Highlights',
    currentWeight: 'Current weight',
    sevenDayChange: '7-day change',
    measurements: 'Measurements',
    latestMeasurement: 'Latest measurement',
    sessions28d: 'Sessions · 28 days',
    workoutsPerWeek: 'Workouts / week',
    volumeTrend: 'Volume trend',
    topExercise: 'Most trained exercise',
    activeDays28d: 'Active days · 28 days',
    sessions7d: 'Sessions · 7 days',
    latestWorkout: 'Latest workout',
    recentRecords: 'Recent estimated 1RM records',
    improvingExercises: 'Exercises trending up',
    decliningExercises: 'Exercises trending down',
    noTrainingEvidence: 'Complete workouts to unlock training highlights.',
    noBodyData: 'Add weight or measurements to build a body baseline.',
    noTrainingData: 'Complete a workout to build strength and training trends.',
    noActivityData: 'No completed workouts in this period.',
    addMeasurement: 'Add measurement',
    hideMeasurementEditor: 'Close measurement editor',
    openWorkoutHistory: 'Workout history',
    up: 'Up',
    down: 'Down',
    stable: 'Stable',
    insufficientData: 'Not enough data',
    notAvailable: '—',
  },
  ru: {
    body: 'Тело',
    strengthTraining: 'Сила и тренировки',
    activity: 'Активность',
    activityDetails: 'Подробнее об активности',
    highlights: 'Главное',
    currentWeight: 'Текущий вес',
    sevenDayChange: 'Изменение за 7 дней',
    measurements: 'Измерения',
    latestMeasurement: 'Последнее измерение',
    sessions28d: 'Тренировки · 28 дней',
    workoutsPerWeek: 'Тренировок / нед.',
    volumeTrend: 'Тренд объёма',
    topExercise: 'Самое частое упражнение',
    activeDays28d: 'Активные дни · 28 дней',
    sessions7d: 'Тренировки · 7 дней',
    latestWorkout: 'Последняя тренировка',
    recentRecords: 'Новые расчётные рекорды 1ПМ',
    improvingExercises: 'Упражнения с ростом',
    decliningExercises: 'Упражнения со снижением',
    noTrainingEvidence: 'Завершите тренировки, чтобы появились основные сигналы прогресса.',
    noBodyData: 'Добавьте вес или измерения, чтобы сформировать базовую линию.',
    noTrainingData: 'Завершите тренировку, чтобы появились силовые и тренировочные тренды.',
    noActivityData: 'В этом периоде нет завершённых тренировок.',
    addMeasurement: 'Добавить измерение',
    hideMeasurementEditor: 'Закрыть форму измерения',
    openWorkoutHistory: 'История тренировок',
    up: 'Рост',
    down: 'Снижение',
    stable: 'Стабильно',
    insufficientData: 'Недостаточно данных',
    notAvailable: '—',
  },
} as const;

export const getProgressOverviewCopy = (locale: SupportedLocale) => copy[locale];
