import { StyleSheet } from "react-native";

import {
  Colors,
  MaxContentWidth,
  Radii,
  Spacing,
  Typography,
} from "@/constants/theme";

export const createSocialWorkoutPostSurfaceStyles = (
  colors: typeof Colors.dark,
) =>
  StyleSheet.create({
    backButton: {
      alignItems: "center",
      borderColor: colors.borderSubtle,
      borderRadius: Radii.large,
      borderWidth: StyleSheet.hairlineWidth,
      flexShrink: 0,
      height: 44,
      justifyContent: "center",
      width: 44,
    },
    body: {
      color: colors.textSecondary,
      flexShrink: 1,
      fontSize: Typography.body.fontSize,
      lineHeight: Typography.body.lineHeight,
    },
    caption: {
      color: colors.textPrimary,
      flexShrink: 1,
      fontSize: Typography.body.fontSize,
      lineHeight: Typography.body.lineHeight,
    },
    cardTitle: {
      color: colors.textPrimary,
      flexShrink: 1,
      fontSize: Typography.cardTitle.fontSize,
      fontWeight: Typography.cardTitle.fontWeight,
      lineHeight: Typography.cardTitle.lineHeight,
    },
    commentActions: {
      alignItems: "center",
      flexDirection: "row",
      flexShrink: 1,
      flexWrap: "wrap",
      gap: Spacing.one,
      justifyContent: "flex-end",
    },
    commentBody: {
      color: colors.textPrimary,
      flexShrink: 1,
      fontSize: Typography.body.fontSize,
      lineHeight: Typography.body.lineHeight,
    },
    commentCard: {
      backgroundColor: colors.backgroundSelected,
      borderColor: colors.borderSubtle,
      borderCurve: "continuous",
      borderRadius: Radii.medium,
      borderWidth: StyleSheet.hairlineWidth,
      gap: Spacing.two,
      padding: Spacing.three,
    },
    commentDeleteButton: {
      alignItems: "center",
      justifyContent: "center",
      minHeight: 44,
      paddingHorizontal: Spacing.two,
    },
    commentDeleteLabel: {
      color: colors.error,
      flexShrink: 1,
      fontSize: Typography.caption.fontSize,
      fontWeight: "700",
      lineHeight: Typography.caption.lineHeight,
    },
    commentHeader: {
      alignItems: "flex-start",
      flexDirection: "row",
      flexWrap: "wrap",
      gap: Spacing.two,
      justifyContent: "space-between",
    },
    commentHeaderCopy: { flex: 1, gap: 2, minWidth: 0 },
    commentInput: { minHeight: 96 },
    commentReportButton: {
      alignItems: "center",
      justifyContent: "center",
      minHeight: 44,
      paddingHorizontal: Spacing.two,
    },
    commentReportLabel: {
      color: colors.textSecondary,
      flexShrink: 1,
      fontSize: Typography.caption.fontSize,
      fontWeight: "700",
      lineHeight: Typography.caption.lineHeight,
    },
    container: { gap: Spacing.four, maxWidth: MaxContentWidth, width: "100%" },
    content: {
      alignItems: "center",
      flexGrow: 1,
      paddingHorizontal: Spacing.four,
    },
    detailLabel: {
      color: colors.textSecondary,
      flexShrink: 1,
      fontSize: Typography.caption.fontSize,
      fontWeight: "700",
      letterSpacing: 0.5,
      textTransform: "uppercase",
    },
    detailValue: {
      color: colors.textPrimary,
      flexShrink: 1,
      fontSize: Typography.body.fontSize,
      lineHeight: Typography.body.lineHeight,
    },
    exerciseCard: { gap: Spacing.three },
    exerciseName: {
      color: colors.textPrimary,
      flexShrink: 1,
      fontSize: Typography.cardTitle.fontSize,
      fontWeight: Typography.cardTitle.fontWeight,
      lineHeight: Typography.cardTitle.lineHeight,
    },
    eyebrow: {
      color: colors.accent,
      flexShrink: 1,
      fontSize: Typography.caption.fontSize,
      fontWeight: "800",
      letterSpacing: 1.2,
    },
    headerCopy: { flex: 1, gap: Spacing.one, minWidth: 0 },
    headerRow: {
      alignItems: "flex-start",
      flexDirection: "row",
      gap: Spacing.three,
    },
    metaText: {
      color: colors.textSecondary,
      flexShrink: 1,
      fontSize: Typography.caption.fontSize,
      lineHeight: Typography.caption.lineHeight,
    },
    metric: {
      backgroundColor: colors.backgroundSelected,
      borderRadius: Radii.medium,
      flexGrow: 1,
      gap: 2,
      minWidth: 88,
      padding: Spacing.three,
    },
    metricLabel: {
      color: colors.textSecondary,
      flexShrink: 1,
      fontSize: Typography.caption.fontSize,
      lineHeight: Typography.caption.lineHeight,
    },
    metricRow: { flexDirection: "row", flexWrap: "wrap", gap: Spacing.two },
    metricValue: {
      color: colors.textPrimary,
      flexShrink: 1,
      fontSize: Typography.label.fontSize,
      fontWeight: Typography.label.fontWeight,
      lineHeight: Typography.label.lineHeight,
    },
    postCard: { gap: Spacing.three },
    postHeader: {
      alignItems: "flex-start",
      flexDirection: "row",
      gap: Spacing.three,
    },
    postHeaderCopy: { flex: 1, gap: Spacing.one, minWidth: 0 },
    postImage: { height: "100%", width: "100%" },
    postImageFrame: {
      borderCurve: "continuous",
      borderRadius: Radii.medium,
      overflow: "hidden",
      width: "100%",
    },
    postTitle: {
      color: colors.textPrimary,
      flexShrink: 1,
      fontSize: Typography.cardTitle.fontSize,
      fontWeight: Typography.cardTitle.fontWeight,
      lineHeight: Typography.cardTitle.lineHeight,
    },
    pressed: { opacity: 0.72 },
    screen: { backgroundColor: colors.background, flex: 1 },
    setRow: {
      alignItems: "center",
      borderTopColor: colors.borderSubtle,
      borderTopWidth: StyleSheet.hairlineWidth,
      flexDirection: "row",
      flexWrap: "wrap",
      gap: Spacing.three,
      paddingTop: Spacing.two,
    },
    subtitle: {
      color: colors.textSecondary,
      flexShrink: 1,
      fontSize: Typography.body.fontSize,
      lineHeight: Typography.body.lineHeight,
    },
    title: {
      color: colors.textPrimary,
      flexShrink: 1,
      fontSize: Typography.screenTitle.fontSize,
      fontWeight: Typography.screenTitle.fontWeight,
      letterSpacing: Typography.screenTitle.letterSpacing,
      lineHeight: Typography.screenTitle.lineHeight,
    },
    username: {
      color: colors.accent,
      flexShrink: 1,
      fontSize: Typography.caption.fontSize,
      fontWeight: "700",
      lineHeight: Typography.caption.lineHeight,
    },
  });

export type SocialWorkoutPostSurfaceStyles = ReturnType<
  typeof createSocialWorkoutPostSurfaceStyles
>;
