import { StyleSheet } from 'react-native';

import { Colors, MaxContentWidth, Radii, Spacing } from '@/constants/theme';
import type { LiquidGlassPalette } from '@/theme/liquidGlass';

export const createStyles = (colors: typeof Colors.dark, glass: LiquidGlassPalette) =>
  StyleSheet.create({
    accentPressed: {
      backgroundColor: glass.accentPressedFill,
    },
    addButton: {
      alignItems: 'center',
      backgroundColor: glass.controlFill,
      borderColor: glass.controlBorder,
      borderCurve: 'continuous',
      borderRadius: 999,
      borderWidth: StyleSheet.hairlineWidth,
      height: 36,
      justifyContent: 'center',
      width: 36,
    },
    addButtonText: {
      color: colors.textPrimary,
      fontSize: 16,
      fontWeight: '900',
      lineHeight: 16,
    },
    calendarButton: {
      alignItems: 'center',
      backgroundColor: glass.controlFill,
      borderColor: glass.controlBorder,
      borderCurve: 'continuous',
      borderRadius: 999,
      borderWidth: StyleSheet.hairlineWidth,
      height: 44,
      justifyContent: 'center',
      minWidth: 44,
      paddingHorizontal: Spacing.two,
    },
    container: {
      gap: Spacing.three,
      maxWidth: MaxContentWidth,
      width: '100%',
    },
    content: {
      alignItems: 'center',
      paddingHorizontal: Spacing.three,
      paddingTop: Spacing.three,
    },
    controlPressed: {
      backgroundColor: glass.controlPressedFill,
    },
    foodList: {
      backgroundColor: glass.cardFill,
      borderTopColor: glass.cardBorder,
      borderTopWidth: StyleSheet.hairlineWidth,
      gap: 0,
      paddingHorizontal: Spacing.three,
      paddingVertical: Spacing.one,
    },
    foodRow: {
      gap: 0,
      minHeight: 44,
    },
    foodRowTop: {
      alignItems: 'flex-start',
      flexDirection: 'row',
      gap: Spacing.one,
    },
    foodRowCopy: {
      flex: 1,
      gap: 0,
      minWidth: 0,
    },
    foodRowDetail: {
      color: colors.textSecondary,
      fontSize: 12,
      lineHeight: 16,
    },
    foodRowDivider: {
      borderTopColor: colors.borderSubtle,
      borderTopWidth: StyleSheet.hairlineWidth,
      paddingTop: Spacing.one,
    },
    foodRowTitle: {
      color: colors.textPrimary,
      fontSize: 14,
      fontWeight: '800',
    },
    detailLabel: {
      color: colors.textPrimary,
      flex: 1,
      fontSize: 14,
      fontWeight: '800',
      minWidth: 0,
    },
    detailRow: {
      alignItems: 'center',
      borderTopColor: colors.borderSubtle,
      borderTopWidth: StyleSheet.hairlineWidth,
      flexDirection: 'row',
      gap: Spacing.two,
      justifyContent: 'space-between',
      paddingVertical: Spacing.two,
    },
    detailValue: {
      color: colors.textPrimary,
      fontSize: 14,
      fontWeight: '800',
      fontVariant: ['tabular-nums'],
    },
    detailsSection: {
      gap: Spacing.one,
    },
    headerRow: {
      alignItems: 'center',
      flexDirection: 'row',
      justifyContent: 'space-between',
      gap: Spacing.two,
      minHeight: 44,
    },
    mealActionButton: {
      alignItems: 'center',
      backgroundColor: glass.controlFill,
      borderColor: glass.controlBorder,
      borderCurve: 'continuous',
      borderRadius: 999,
      borderWidth: StyleSheet.hairlineWidth,
      height: 36,
      justifyContent: 'center',
      width: 36,
    },
    mealGroup: {
      backgroundColor: glass.cardFill,
      borderColor: glass.cardBorder,
      borderCurve: 'continuous',
      borderRadius: Radii.medium,
      borderWidth: StyleSheet.hairlineWidth,
      overflow: 'hidden',
    },
    mealHeader: {
      alignItems: 'center',
      flexDirection: 'row',
      gap: Spacing.two,
      justifyContent: 'space-between',
      minHeight: 52,
      paddingHorizontal: Spacing.three,
      paddingVertical: Spacing.two,
    },
    mealHeaderActions: {
      alignItems: 'center',
      flexDirection: 'row',
      gap: Spacing.one,
    },
    mealHeaderCopy: {
      flex: 1,
      gap: 1,
      minWidth: 0,
    },
    mealHeaderLeft: {
      alignItems: 'center',
      flex: 1,
      flexDirection: 'row',
      gap: Spacing.two,
      minWidth: 0,
    },
    mealHeaderMeta: {
      color: colors.textSecondary,
      fontSize: 12,
      fontWeight: '700',
      lineHeight: 16,
    },
    mealIcon: {
      color: colors.textSecondary,
      fontSize: 14,
      fontWeight: '900',
      width: 16,
    },
    mealList: {
      gap: Spacing.two,
    },
    mealSectionList: {
      gap: Spacing.two,
      marginTop: Spacing.two,
    },
    mealSummaryStrip: {
      backgroundColor: glass.controlFill,
      borderTopColor: glass.controlBorder,
      borderTopWidth: StyleSheet.hairlineWidth,
    },
    mealTitle: {
      color: colors.textPrimary,
      fontSize: 15,
      fontWeight: '800',
    },
    metaRow: {
      alignItems: 'center',
      flexDirection: 'row',
      justifyContent: 'space-between',
      gap: Spacing.two,
      minHeight: 36,
    },
    nutrientCard: {
      paddingVertical: Spacing.two,
    },
    nutrientCardCopy: {
      flex: 1,
      gap: 2,
      minWidth: 0,
    },
    nutrientCardRow: {
      alignItems: 'center',
      flexDirection: 'row',
      justifyContent: 'space-between',
      gap: Spacing.two,
    },
    nutrientHint: {
      color: colors.textSecondary,
      fontSize: 12,
      lineHeight: 16,
    },
    nutrientLabel: {
      color: colors.textPrimary,
      fontSize: 14,
      fontWeight: '800',
    },
    nutrientValue: {
      color: colors.textPrimary,
      fontSize: 16,
      fontWeight: '900',
      fontVariant: ['tabular-nums'],
    },
    screen: {
      backgroundColor: colors.background,
      flex: 1,
    },
    sectionHeader: {
      marginBottom: Spacing.one,
    },
    sectionTitle: {
      color: colors.textPrimary,
      fontSize: 18,
      fontWeight: '800',
    },
    streakChip: {
      alignItems: 'center',
      alignSelf: 'flex-start',
      backgroundColor: glass.controlFill,
      borderColor: glass.controlBorder,
      borderCurve: 'continuous',
      borderRadius: 999,
      borderWidth: StyleSheet.hairlineWidth,
      flexDirection: 'row',
      gap: Spacing.one,
      minHeight: 36,
      paddingHorizontal: Spacing.two,
    },
    streakEmoji: {
      color: colors.textPrimary,
      fontSize: 13,
      fontWeight: '900',
    },
    streakText: {
      color: colors.textPrimary,
      fontSize: 12,
      fontWeight: '800',
    },
    summarySection: {
      backgroundColor: glass.cardFill,
      borderColor: glass.cardBorder,
      borderCurve: 'continuous',
      borderRadius: Radii.medium,
      borderWidth: StyleSheet.hairlineWidth,
      overflow: 'hidden',
    },
    macroGridRow: {
      flexDirection: 'row',
      gap: 0,
      paddingHorizontal: Spacing.three,
      paddingVertical: Spacing.two,
    },
    macroGridRowNested: {
      paddingHorizontal: 0,
    },
    macroGridCell: {
      alignItems: 'center',
      gap: 2,
      minWidth: 0,
      paddingHorizontal: Spacing.one,
    },
    macroGridCellWithBorder: {
      borderLeftColor: glass.controlBorder,
      borderLeftWidth: StyleSheet.hairlineWidth,
    },
    macroGridLabel: {
      color: colors.textSecondary,
      fontSize: 9,
      fontWeight: '800',
      lineHeight: 11,
      textAlign: 'center',
      textTransform: 'uppercase',
    },
    macroGridValue: {
      color: colors.textPrimary,
      fontSize: 13,
      fontWeight: '800',
      fontVariant: ['tabular-nums'],
      lineHeight: 16,
      textAlign: 'center',
    },
    title: {
      color: colors.textPrimary,
      fontSize: 24,
      fontWeight: '900',
    },
    todayButton: {
      alignItems: 'center',
      backgroundColor: glass.controlFill,
      borderColor: glass.controlBorder,
      borderCurve: 'continuous',
      borderRadius: 999,
      borderWidth: StyleSheet.hairlineWidth,
      height: 36,
      justifyContent: 'center',
      minWidth: 72,
      paddingHorizontal: Spacing.two,
    },
    todayButtonDisabled: {
      backgroundColor: glass.disabledFill,
      borderColor: glass.disabledBorder,
    },
    todayButtonText: {
      color: colors.textPrimary,
      fontSize: 13,
      fontWeight: '800',
    },
    todayButtonTextDisabled: {
      color: colors.textMuted,
    },
    weekDayButton: {
      alignItems: 'center',
      flex: 1,
      gap: 2,
      justifyContent: 'center',
      minHeight: 44,
      paddingVertical: 0,
    },
    weekDayCircle: {
      alignItems: 'center',
      backgroundColor: glass.controlFill,
      borderColor: glass.controlBorder,
      borderCurve: 'continuous',
      borderRadius: 999,
      borderWidth: StyleSheet.hairlineWidth,
      height: 22,
      justifyContent: 'center',
      width: 22,
    },
    weekDayCircleSelected: {
      backgroundColor: glass.accentFill,
      borderColor: glass.accentBorder,
    },
    weekDayCircleLogged: {
      borderColor: glass.accentBorder,
      borderWidth: 1,
    },
    weekDayCircleToday: {
      borderColor: glass.accentBorder,
      borderWidth: 1,
    },
    weekDayCircleTodaySelected: {
      borderColor: glass.accentText,
    },
    weekDayCheck: {
      color: colors.accent,
      fontSize: 9,
      fontWeight: '900',
    },
    weekDayCheckSelected: {
      color: glass.accentText,
    },
    weekDayHitArea: {
      alignItems: 'center',
      height: 28,
      justifyContent: 'center',
      width: 28,
    },
    weekDayLabel: {
      color: colors.textSecondary,
      fontSize: 10,
      fontWeight: '800',
      lineHeight: 12,
      textTransform: 'uppercase',
    },
    weekDayLabelSelected: {
      color: colors.textPrimary,
    },
    weekDayTodayDot: {
      backgroundColor: colors.accent,
      borderRadius: 999,
      height: 5,
      width: 5,
    },
    weekDayTodayDotSelected: {
      backgroundColor: glass.accentText,
    },
    weekSection: {
      borderBottomColor: glass.cardBorder,
      borderBottomWidth: StyleSheet.hairlineWidth,
      borderTopColor: glass.cardBorder,
      borderTopWidth: StyleSheet.hairlineWidth,
      paddingVertical: Spacing.one,
    },
    weekStrip: {
      flexDirection: 'row',
      gap: 0,
      paddingHorizontal: 0,
    },
  });
