import type { SupportedLocale } from "@/localization";

export const getShareWorkoutCopy = (locale: SupportedLocale) =>
  locale === "ru"
    ? {
        title: "Поделиться тренировкой",
        subtitle: "Выберите только те данные, которые хотите опубликовать.",
        loading: "Загрузка тренировки…",
        caption: "Подпись",
        captionPlaceholder: "Что хотите рассказать об этой тренировке?",
        preview: "Предпросмотр",
        fields: "Публичные данные",
        workoutTitle: "Название тренировки",
        duration: "Продолжительность",
        exercises: "Упражнения",
        sets: "Подходы",
        load: "Вес",
        repetitions: "Повторения",
        rpe: "RPE",
        volume: "Общий объём",
        minutes: (count: number) => `${count} мин`,
        exerciseCount: (count: number) => `${count} упр.`,
        setCount: (count: number) => `${count} подх.`,
        volumeValue: (value: number) => `${Math.round(value)} кг`,
        detailsHidden: "Детали подходов скрыты",
        imageTitle: "Фото тренировки",
        imageOptional: "Необязательно. Можно добавить одно фото.",
        chooseImage: "Выбрать фото",
        replaceImage: "Заменить фото",
        removeImage: "Убрать фото",
        refreshImage: "Обновить статус",
        imageWaiting:
          "Фото ещё не одобрено. Дождитесь обработки или уберите его перед публикацией.",
        selectingImage: "Выбор фото…",
        preparingImage: "Подготовка фото…",
        uploadingImage: "Загрузка фото…",
        completingImage: "Проверка загрузки…",
        processingImage: "Обработка фото…",
        removingImage: "Удаление фото…",
        imageUploadPending: "Фото ожидает загрузки.",
        imageQuarantined: "Фото загружено и проходит проверку.",
        imageReviewRequired:
          "Фото ожидает ручной проверки и пока не публикуется.",
        imageApproved: "Фото одобрено и будет добавлено к публикации.",
        imageRejected: "Фото отклонено. Выберите другое или удалите его.",
        imageFailed:
          "Не удалось обработать фото. Выберите другое или повторите позже.",
        imageDeleted: "Фото удалено и не будет опубликовано.",
        imagePermissionDenied:
          "Разрешите доступ к медиатеке, чтобы выбрать фото.",
        imageSelectionFailed: "Не удалось выбрать фото.",
        imageUnsupported: "Выбранный файл не поддерживается.",
        imageProcessingFailed: "Не удалось подготовить фото к загрузке.",
        imageTooLarge: "Фото остаётся слишком большим после сжатия.",
        imageUploadExpired: "Ссылка загрузки истекла. Выберите фото ещё раз.",
        imageUploadUnavailable: "Загрузка фото сейчас недоступна.",
        imageValidationFailed: "Сервер не принял это фото. Выберите другое.",
        imageOffline: "Нет соединения для загрузки фото.",
        imageSessionExpired: "Сессия истекла. Войдите снова.",
        imageStale: "Статус фото изменился. Обновите его и повторите попытку.",
        imageAlreadyAttached: "Это фото уже используется в другой публикации.",
        imageGenericError: "Не удалось обработать фото. Повторите попытку.",
        publish: "Опубликовать",
        publishTitle: "Опубликовать тренировку?",
        publishBody:
          "Будет создан отдельный неизменяемый публичный снимок. Изменения личной тренировки не изменят публикацию.",
        publishConfirm: "Опубликовать",
        publishing: "Синхронизация и публикация…",
        successTitle: "Тренировка опубликована",
        successBody: "Публикация сохранена в вашем социальном профиле.",
        done: "Готово",
        signInTitle: "Нужен аккаунт",
        signInBody:
          "Войдите, чтобы синхронизировать и опубликовать тренировку.",
        signIn: "Войти",
        profileTitle: "Создайте социальный профиль",
        profileBody:
          "Перед первой публикацией выберите username и видимость профиля.",
        createProfile: "Создать профиль",
        missingTitle: "Тренировка не найдена",
        missingBody: "Локальная завершённая тренировка больше недоступна.",
        sourceNotReady:
          "Тренировка ещё не появилась на сервере. Проверьте подключение и повторите публикацию.",
        offline:
          "Нет соединения. Подключитесь к интернету и повторите попытку.",
        sessionExpired: "Сессия истекла. Войдите снова.",
        unavailable: "Эту тренировку нельзя опубликовать с выбранными данными.",
        genericError: "Не удалось опубликовать тренировку. Повторите попытку.",
        emptyError: "Выберите хотя бы одно поле или добавьте подпись.",
        retry: "Повторить",
        back: "Назад",
      }
    : {
        title: "Share workout",
        subtitle: "Choose only the details you want to make public.",
        loading: "Loading workout…",
        caption: "Caption",
        captionPlaceholder: "What would you like to say about this workout?",
        preview: "Preview",
        fields: "Public details",
        workoutTitle: "Workout title",
        duration: "Duration",
        exercises: "Exercises",
        sets: "Sets",
        load: "Load",
        repetitions: "Repetitions",
        rpe: "RPE",
        volume: "Total volume",
        minutes: (count: number) => `${count} min`,
        exerciseCount: (count: number) => `${count} exercises`,
        setCount: (count: number) => `${count} sets`,
        volumeValue: (value: number) => `${Math.round(value)} kg`,
        detailsHidden: "Set details hidden",
        imageTitle: "Workout photo",
        imageOptional: "Optional. You can add one photo.",
        chooseImage: "Choose photo",
        replaceImage: "Replace photo",
        removeImage: "Remove photo",
        refreshImage: "Refresh status",
        imageWaiting:
          "The photo is not approved yet. Wait for processing or remove it before publishing.",
        selectingImage: "Choosing photo…",
        preparingImage: "Preparing photo…",
        uploadingImage: "Uploading photo…",
        completingImage: "Verifying upload…",
        processingImage: "Processing photo…",
        removingImage: "Removing photo…",
        imageUploadPending: "The photo is waiting to upload.",
        imageQuarantined: "The photo is uploaded and being checked.",
        imageReviewRequired: "The photo needs review and is not public yet.",
        imageApproved: "The photo is approved and will be added to the post.",
        imageRejected: "The photo was rejected. Choose another or remove it.",
        imageFailed:
          "The photo could not be processed. Choose another or retry later.",
        imageDeleted: "The photo was removed and will not be published.",
        imagePermissionDenied: "Allow photo-library access to choose an image.",
        imageSelectionFailed: "The photo could not be selected.",
        imageUnsupported: "The selected file is not supported.",
        imageProcessingFailed: "The photo could not be prepared for upload.",
        imageTooLarge: "The photo is still too large after compression.",
        imageUploadExpired: "The upload link expired. Choose the photo again.",
        imageUploadUnavailable: "Photo uploads are currently unavailable.",
        imageValidationFailed:
          "The server rejected this photo. Choose another.",
        imageOffline: "You are offline. Reconnect to upload the photo.",
        imageSessionExpired: "Your session expired. Sign in again.",
        imageStale: "The photo state changed. Refresh it and retry.",
        imageAlreadyAttached: "This photo is already attached to another post.",
        imageGenericError: "The photo could not be processed. Try again.",
        publish: "Publish",
        publishTitle: "Publish this workout?",
        publishBody:
          "A separate immutable public snapshot will be created. Later edits to the private workout will not change the post.",
        publishConfirm: "Publish",
        publishing: "Syncing and publishing…",
        successTitle: "Workout published",
        successBody: "The post is now saved to your social profile.",
        done: "Done",
        signInTitle: "Account required",
        signInBody: "Sign in to synchronize and publish this workout.",
        signIn: "Sign in",
        profileTitle: "Create a social profile",
        profileBody:
          "Choose a username and profile visibility before your first post.",
        createProfile: "Create profile",
        missingTitle: "Workout not found",
        missingBody: "The completed local workout is no longer available.",
        sourceNotReady:
          "The workout has not reached the server yet. Check your connection and retry publishing.",
        offline: "You are offline. Reconnect and try again.",
        sessionExpired: "Your session expired. Sign in again.",
        unavailable:
          "This workout cannot be published with the selected details.",
        genericError: "The workout could not be published. Try again.",
        emptyError: "Select at least one workout field or add a caption.",
        retry: "Retry",
        back: "Back",
      };
