import { StyleSheet } from 'react-native';

import { Colors, MaxContentWidth, Radii, Spacing } from '@/constants/theme';
import {
  SESSION_TABLE_COLUMNS,
  SESSION_TABLE_GAPS,
  SESSION_TABLE_TOTAL_WIDTH,
} from '@/features/workouts/components/session/sessionTableLayout';
import type { LiquidGlassPalette } from '@/theme/liquidGlass';

export const createStyles = (colors: typeof Colors.light, glass: LiquidGlassPalette) =>
  StyleSheet.create({
    addButton: {
      alignItems: 'center',
      alignSelf: 'stretch',
      backgroundColor: glass.accentFill,
      borderColor: glass.accentBorder,
      borderCurve: 'continuous',
      borderRadius: 999,
      borderWidth: StyleSheet.hairlineWidth,
      justifyContent: 'center',
      minHeight: 58,
      overflow: 'hidden',
      paddingHorizontal: Spacing.three,
    },
    addButtonLabel: {
      color: glass.accentText,
      flexShrink: 1,
      fontSize: 16,
      fontWeight: '700',
      textAlign: 'center',
    },
    addButtonPressed: {
      backgroundColor: glass.accentPressedFill,
    },
    addSetButton: {
      alignItems: 'center',
      alignSelf: 'center',
      backgroundColor: glass.controlFill,
      borderColor: glass.controlBorder,
      borderCurve: 'continuous',
      borderRadius: 999,
      borderWidth: StyleSheet.hairlineWidth,
      justifyContent: 'center',
      minHeight: 46,
      width: '92%',
    },
    addSetButtonPressed: {
      backgroundColor: glass.controlPressedFill,
    },
    addSetLabel: {
      color: colors.textPrimary,
      flexShrink: 1,
      fontSize: 16,
      fontWeight: '500',
      textAlign: 'center',
    },
    centerState: {
      alignItems: 'center',
      justifyContent: 'center',
      padding: Spacing.three,
    },
    check: {
      color: colors.accent,
      flexShrink: 0,
      fontSize: 20,
      fontWeight: '900',
      width: 24,
    },
    collapsedSetLine: {
      color: colors.textSecondary,
      flexShrink: 1,
      fontSize: 15,
      fontVariant: ['tabular-nums'],
      lineHeight: 22,
      minWidth: 0,
    },
    colPrevious: {
      flexBasis: 0,
      flexGrow: SESSION_TABLE_COLUMNS.previous,
      marginLeft: SESSION_TABLE_GAPS.setToPrevious,
      minWidth: 0,
    },
    colReps: {
      flexBasis: 0,
      flexGrow: SESSION_TABLE_COLUMNS.reps,
      marginLeft: SESSION_TABLE_GAPS.weightToReps,
      minWidth: 0,
    },
    colSet: {
      flexShrink: 0,
      width: SESSION_TABLE_COLUMNS.set,
    },
    colWeight: {
      flexBasis: 0,
      flexGrow: SESSION_TABLE_COLUMNS.weight,
      marginLeft: SESSION_TABLE_GAPS.previousToWeight,
      minWidth: 0,
    },
    container: {
      alignSelf: 'center',
      maxWidth: MaxContentWidth,
      minWidth: 0,
      width: '100%',
    },
    content: {
      flexGrow: 1,
      minWidth: 0,
      paddingHorizontal: Spacing.four,
      paddingTop: Spacing.four,
      width: '100%',
    },
    deleteLabel: {
      color: colors.error,
    },
    deleteMenuActionPressed: {
      backgroundColor: colors.errorSoft,
    },
    disabled: {
      opacity: 0.35,
    },
    emptyBlock: {
      alignItems: 'center',
      gap: Spacing.three,
      paddingHorizontal: Spacing.five,
      paddingVertical: Spacing.eight,
    },
    emptyText: {
      color: colors.textPrimary,
      fontSize: 18,
      lineHeight: 26,
      textAlign: 'center',
    },
    emptyTitle: {
      color: colors.textPrimary,
      fontSize: 20,
      fontWeight: '900',
      lineHeight: 26,
      textAlign: 'center',
    },
    exerciseBlock: {
      gap: 0,
    },
    exerciseCopy: {
      flex: 1,
      minWidth: 0,
    },
    exerciseHeaderPressed: {
      backgroundColor: glass.controlPressedFill,
    },
    exerciseHeaderRow: {
      alignItems: 'flex-start',
      borderCurve: 'continuous',
      borderRadius: 12,
      flexDirection: 'row',
      gap: 13,
      minWidth: 0,
      paddingBottom: 24,
    },
    exerciseHelp: {
      bottom: 2,
      color: colors.textMuted,
      fontSize: 10,
      position: 'absolute',
      right: 5,
    },
    exerciseList: {
      gap: Spacing.four,
      paddingVertical: Spacing.five,
    },
    exerciseMenuButton: {
      alignItems: 'center',
      borderCurve: 'continuous',
      borderRadius: 17,
      flexShrink: 0,
      height: 34,
      justifyContent: 'center',
      width: 34,
    },
    exerciseMenuButtonPressed: {
      backgroundColor: glass.semanticAccentFill,
    },
    exerciseMenuLabel: {
      color: colors.accent,
      fontSize: 14,
      fontWeight: '900',
      letterSpacing: 1.4,
      lineHeight: 18,
    },
    exerciseNotesInput: {
      color: colors.textMuted,
      fontSize: 15,
      lineHeight: 22,
      minHeight: 22,
      paddingVertical: 0,
    },
    exerciseThumb: {
      alignItems: 'center',
      backgroundColor: '#FFFFFF',
      borderColor: '#F3F3F3',
      borderCurve: 'continuous',
      borderRadius: 7,
      borderWidth: StyleSheet.hairlineWidth,
      flexShrink: 0,
      height: 66,
      justifyContent: 'center',
      width: 44,
    },
    exerciseThumbLabel: {
      color: '#111111',
      fontSize: 16,
      fontWeight: '900',
    },
    exerciseTitle: {
      color: colors.textPrimary,
      flexShrink: 1,
      fontSize: 17,
      fontWeight: '500',
      lineHeight: 22,
    },
    expandedPanel: {
      gap: 15,
      minWidth: 0,
      paddingBottom: 34,
      width: '100%',
    },
    header: {
      alignItems: 'center',
      borderBottomColor: glass.cardBorder,
      borderBottomWidth: StyleSheet.hairlineWidth,
      flexDirection: 'row',
      gap: Spacing.two,
      minWidth: 0,
      paddingBottom: Spacing.two,
      paddingHorizontal: Spacing.four,
      width: '100%',
    },
    headerTitle: {
      color: colors.textPrimary,
      flex: 1,
      flexShrink: 1,
      fontSize: 18,
      fontWeight: '900',
      minWidth: 0,
      textAlign: 'center',
    },
    list: {
      flex: 1,
      minWidth: 0,
      width: '100%',
    },
    menuAction: {
      borderCurve: 'continuous',
      borderRadius: Radii.medium,
      justifyContent: 'center',
      minHeight: 50,
      paddingHorizontal: Spacing.one,
    },
    menuActionLabel: {
      color: colors.textPrimary,
      flexShrink: 1,
      fontSize: 17,
      fontWeight: '800',
    },
    menuActionPressed: {
      backgroundColor: glass.controlPressedFill,
    },
    menuOverlay: {
      ...StyleSheet.absoluteFill,
      backgroundColor: colors.overlay,
      justifyContent: 'flex-end',
      paddingHorizontal: Spacing.three,
    },
    menuPanel: {
      gap: Spacing.one,
      padding: Spacing.three,
    },
    menuPanelHitArea: {
      borderCurve: 'continuous',
      borderRadius: 22,
    },
    menuTitle: {
      color: colors.textPrimary,
      flexShrink: 1,
      fontSize: 18,
      fontWeight: '900',
      marginBottom: Spacing.one,
    },
    navButton: {
      alignItems: 'center',
      borderCurve: 'continuous',
      borderRadius: Radii.medium,
      flexShrink: 0,
      justifyContent: 'center',
      minHeight: 44,
      paddingHorizontal: Spacing.one,
      width: 90,
    },
    navButtonLabel: {
      color: colors.accent,
      flexShrink: 1,
      fontSize: 16,
      fontWeight: '600',
      textAlign: 'center',
    },
    navButtonPressed: {
      backgroundColor: glass.semanticAccentFill,
    },
    notesInput: {
      color: colors.textSecondary,
      fontSize: 15,
      lineHeight: 22,
      minHeight: 32,
      paddingVertical: 0,
    },
    pickerHeader: {
      alignItems: 'center',
      flexDirection: 'row',
      gap: Spacing.two,
      justifyContent: 'space-between',
      paddingBottom: Spacing.three,
    },
    pickerList: {
      flexShrink: 1,
      minHeight: 0,
    },
    pickerOverlay: {
      ...StyleSheet.absoluteFill,
      backgroundColor: colors.overlay,
      justifyContent: 'flex-end',
    },
    pickerPanel: {
      borderBottomLeftRadius: 0,
      borderBottomRightRadius: 0,
      borderTopLeftRadius: 24,
      borderTopRightRadius: 24,
      maxHeight: '78%',
      padding: Spacing.three,
    },
    pickerRow: {
      alignItems: 'center',
      borderCurve: 'continuous',
      borderRadius: Radii.medium,
      flexDirection: 'row',
      gap: Spacing.three,
      minHeight: 64,
      paddingHorizontal: Spacing.one,
    },
    pickerRowCopy: {
      flex: 1,
      minWidth: 0,
    },
    pickerRowMeta: {
      color: colors.textSecondary,
      flexShrink: 1,
      fontSize: 13,
      fontWeight: '700',
      marginTop: 3,
    },
    pickerRowPressed: {
      backgroundColor: glass.controlPressedFill,
    },
    pickerRowTitle: {
      color: colors.textPrimary,
      flexShrink: 1,
      fontSize: 16,
      fontWeight: '900',
    },
    pickerTitle: {
      color: colors.textPrimary,
      flex: 1,
      flexShrink: 1,
      fontSize: 22,
      fontWeight: '900',
      minWidth: 0,
    },
    planInput: {
      backgroundColor: colors.background,
      borderColor: glass.controlBorder,
      borderCurve: 'continuous',
      borderRadius: 3,
      borderWidth: StyleSheet.hairlineWidth,
      color: colors.textPrimary,
      fontSize: 15,
      fontVariant: ['tabular-nums'],
      fontWeight: '400',
      height: 30,
      includeFontPadding: false,
      lineHeight: 18,
      minWidth: 0,
      paddingHorizontal: 4,
      paddingVertical: 0,
      textAlign: 'center',
    },
    planPrevious: {
      color: colors.textSecondary,
      flexShrink: 1,
      fontSize: 15,
      lineHeight: 48,
      textAlign: 'left',
    },
    planSetRow: {
      alignItems: 'center',
      flexDirection: 'row',
      minHeight: 48,
      minWidth: 0,
      width: '100%',
    },
    planSetText: {
      color: colors.textPrimary,
      fontSize: 15,
      fontWeight: '400',
      lineHeight: 48,
      textAlign: 'center',
    },
    planTable: {
      alignSelf: 'center',
      gap: 8,
      maxWidth: SESSION_TABLE_TOTAL_WIDTH,
      minWidth: 0,
      width: '100%',
    },
    planTableBody: {
      gap: 0,
      minWidth: 0,
      width: '100%',
    },
    planTableHeader: {
      alignItems: 'center',
      flexDirection: 'row',
      minHeight: 22,
      minWidth: 0,
      width: '100%',
    },
    restTimer: {
      color: colors.accent,
      fontSize: 14,
      fontWeight: '400',
      lineHeight: 18,
    },
    screen: {
      backgroundColor: colors.background,
      flex: 1,
      minWidth: 0,
    },
    tableHeaderText: {
      color: colors.textMuted,
      flexShrink: 1,
      fontSize: 13,
      fontWeight: '500',
      lineHeight: 18,
      textAlign: 'center',
    },
    textButton: {
      borderCurve: 'continuous',
      borderRadius: Radii.medium,
      flexShrink: 0,
      justifyContent: 'center',
      maxWidth: 96,
      minHeight: 44,
      paddingHorizontal: Spacing.two,
      paddingVertical: Spacing.two,
    },
    textButtonLabel: {
      color: colors.accent,
      flexShrink: 1,
      fontSize: 16,
      fontWeight: '800',
      textAlign: 'center',
    },
    textButtonPressed: {
      backgroundColor: glass.semanticAccentFill,
    },
    titleInput: {
      color: colors.textPrimary,
      fontSize: 22,
      fontWeight: '800',
      lineHeight: 28,
      minWidth: 0,
      paddingVertical: Spacing.one,
      width: '100%',
    },
  });
