import { StyleSheet } from 'react-native';

import { Colors, MaxContentWidth, Radii, Spacing } from '@/constants/theme';

export const createStyles = (colors: typeof Colors.light) =>
  StyleSheet.create({
    addButton: {
      alignItems: 'center',
      backgroundColor: colors.accent,
      borderCurve: 'continuous',
      borderRadius: 18,
      alignSelf: 'stretch',
      justifyContent: 'center',
      minHeight: 52,
      overflow: 'hidden',
      paddingHorizontal: Spacing.three,
    },
    addButtonLabel: {
      color: colors.textOnAccent,
      flexShrink: 1,
      fontSize: 17,
      fontWeight: '900',
      textAlign: 'center',
    },
    addSetButton: {
      alignItems: 'center',
      backgroundColor: colors.backgroundSecondary,
      borderCurve: 'continuous',
      borderRadius: 999,
      justifyContent: 'center',
      minHeight: 56,
      paddingHorizontal: Spacing.three,
    },
    addSetLabel: {
      color: colors.textPrimary,
      flexShrink: 1,
      fontSize: 17,
      fontWeight: '800',
      textAlign: 'center',
    },
    centerState: {
      alignItems: 'center',
      justifyContent: 'center',
      padding: Spacing.three,
    },
    check: {
      color: colors.accent,
      flexShrink: 0,
      fontSize: 20,
      fontWeight: '900',
      width: 24,
    },
    collapsedSetLine: {
      color: colors.textMuted,
      flexShrink: 1,
      fontSize: 16,
      fontVariant: ['tabular-nums'],
      lineHeight: 24,
    },
    colPrevious: {
      flex: 1.3,
      minWidth: 0,
    },
    colReps: {
      flex: 1,
      minWidth: 0,
    },
    colSet: {
      flexShrink: 0,
      width: 48,
    },
    colWeight: {
      flex: 1,
      minWidth: 0,
    },
    container: {
      maxWidth: MaxContentWidth,
      width: '100%',
    },
    content: {
      alignItems: 'center',
      flexGrow: 1,
      paddingHorizontal: Spacing.three,
      paddingTop: Spacing.six,
    },
    deleteLabel: {
      color: colors.error,
    },
    disabled: {
      opacity: 0.35,
    },
    emptyBlock: {
      alignItems: 'center',
      gap: Spacing.three,
      paddingHorizontal: Spacing.five,
      paddingVertical: Spacing.eight,
    },
    emptyText: {
      color: colors.textPrimary,
      fontSize: 20,
      lineHeight: 28,
      textAlign: 'center',
    },
    emptyTitle: {
      color: colors.textPrimary,
      fontSize: 22,
      fontWeight: '900',
      lineHeight: 28,
      textAlign: 'center',
    },
    exerciseBlock: {
      gap: Spacing.two,
    },
    exerciseCopy: {
      flex: 1,
      minWidth: 0,
    },
    exerciseHeaderRow: {
      alignItems: 'flex-start',
      flexDirection: 'row',
      gap: Spacing.three,
      minHeight: 72,
      paddingVertical: Spacing.one,
    },
    exerciseHelp: {
      bottom: 2,
      color: colors.textMuted,
      fontSize: 10,
      position: 'absolute',
      right: 5,
    },
    exerciseList: {
      gap: Spacing.four,
      paddingVertical: Spacing.five,
    },
    exerciseMenuButton: {
      alignItems: 'center',
      flexShrink: 0,
      height: 42,
      justifyContent: 'center',
      width: 42,
    },
    exerciseMenuLabel: {
      color: colors.accent,
      fontSize: 20,
      fontWeight: '900',
      letterSpacing: 1,
      lineHeight: 22,
    },
    exerciseNotesInput: {
      color: colors.textPrimary,
      fontSize: 18,
      minHeight: 44,
      paddingVertical: Spacing.one,
    },
    exerciseThumb: {
      alignItems: 'center',
      backgroundColor: colors.surfacePrimary,
      borderColor: colors.borderSubtle,
      borderCurve: 'continuous',
      borderRadius: 8,
      borderWidth: StyleSheet.hairlineWidth,
      flexShrink: 0,
      height: 72,
      justifyContent: 'center',
      width: 66,
    },
    exerciseThumbLabel: {
      color: colors.textPrimary,
      fontSize: 22,
      fontWeight: '900',
    },
    exerciseTitle: {
      color: colors.textPrimary,
      flexShrink: 1,
      fontSize: 22,
      fontWeight: '500',
      lineHeight: 29,
    },
    expandedPanel: {
      gap: Spacing.three,
      paddingBottom: Spacing.two,
    },
    header: {
      alignItems: 'center',
      borderBottomColor: colors.borderSubtle,
      borderBottomWidth: StyleSheet.hairlineWidth,
      flexDirection: 'row',
      gap: Spacing.two,
      paddingBottom: Spacing.two,
      paddingHorizontal: Spacing.three,
    },
    headerTitle: {
      color: colors.textPrimary,
      flex: 1,
      flexShrink: 1,
      fontSize: 18,
      fontWeight: '900',
      minWidth: 0,
      textAlign: 'center',
    },
    menuAction: {
      minHeight: 50,
      justifyContent: 'center',
    },
    menuActionLabel: {
      color: colors.textPrimary,
      flexShrink: 1,
      fontSize: 17,
      fontWeight: '800',
    },
    menuOverlay: {
      ...StyleSheet.absoluteFill,
      backgroundColor: colors.overlay,
      justifyContent: 'flex-end',
      paddingHorizontal: Spacing.three,
    },
    menuPanel: {
      gap: Spacing.one,
      padding: Spacing.three,
    },
    menuPanelHitArea: {
      borderCurve: 'continuous',
      borderRadius: 22,
    },
    menuTitle: {
      color: colors.textPrimary,
      flexShrink: 1,
      fontSize: 18,
      fontWeight: '900',
      marginBottom: Spacing.one,
    },
    navButton: {
      alignItems: 'center',
      flexShrink: 0,
      justifyContent: 'center',
      maxWidth: 96,
      minHeight: 44,
      minWidth: 72,
      paddingHorizontal: Spacing.one,
      paddingVertical: Spacing.two,
    },
    navButtonLabel: {
      color: colors.accent,
      flexShrink: 1,
      fontSize: 17,
      fontWeight: '600',
      textAlign: 'center',
    },
    notesInput: {
      color: colors.textPrimary,
      fontSize: 20,
      lineHeight: 28,
      minHeight: 46,
      paddingVertical: Spacing.one,
    },
    pickerHeader: {
      alignItems: 'center',
      flexDirection: 'row',
      gap: Spacing.two,
      justifyContent: 'space-between',
      paddingBottom: Spacing.three,
    },
    pickerList: {
      flexShrink: 1,
      minHeight: 0,
    },
    pickerOverlay: {
      ...StyleSheet.absoluteFill,
      backgroundColor: colors.overlay,
      justifyContent: 'flex-end',
    },
    pickerPanel: {
      borderBottomLeftRadius: 0,
      borderBottomRightRadius: 0,
      borderTopLeftRadius: 24,
      borderTopRightRadius: 24,
      maxHeight: '78%',
      padding: Spacing.three,
    },
    pickerRow: {
      alignItems: 'center',
      flexDirection: 'row',
      gap: Spacing.three,
      minHeight: 64,
    },
    pickerRowCopy: {
      flex: 1,
      minWidth: 0,
    },
    pickerRowMeta: {
      color: colors.textSecondary,
      flexShrink: 1,
      fontSize: 13,
      fontWeight: '700',
      marginTop: 3,
    },
    pickerRowTitle: {
      color: colors.textPrimary,
      flexShrink: 1,
      fontSize: 16,
      fontWeight: '900',
    },
    pickerTitle: {
      color: colors.textPrimary,
      flex: 1,
      flexShrink: 1,
      fontSize: 22,
      fontWeight: '900',
      minWidth: 0,
    },
    planInput: {
      backgroundColor: colors.surfacePrimary,
      borderColor: colors.borderSubtle,
      borderCurve: 'continuous',
      borderRadius: 8,
      borderWidth: StyleSheet.hairlineWidth,
      color: colors.textPrimary,
      fontSize: 17,
      height: 46,
      minWidth: 0,
      paddingHorizontal: Spacing.one,
      textAlign: 'center',
    },
    planPrevious: {
      color: colors.textSecondary,
      flexShrink: 1,
      fontSize: 17,
      lineHeight: 46,
    },
    planSetRow: {
      alignItems: 'center',
      flexDirection: 'row',
      gap: Spacing.three,
    },
    planSetText: {
      color: colors.textPrimary,
      fontSize: 18,
      lineHeight: 46,
    },
    planTableHeader: {
      alignItems: 'center',
      flexDirection: 'row',
      gap: Spacing.three,
    },
    pressed: {
      opacity: 0.72,
    },
    restTimer: {
      color: colors.accent,
      fontSize: 18,
      fontWeight: '800',
    },
    screen: {
      backgroundColor: colors.background,
      flex: 1,
    },
    tableHeaderText: {
      color: colors.textMuted,
      flexShrink: 1,
      fontSize: 15,
      fontWeight: '700',
    },
    textButton: {
      flexShrink: 0,
      justifyContent: 'center',
      maxWidth: 96,
      minHeight: 44,
      paddingHorizontal: Spacing.one,
      paddingVertical: Spacing.two,
    },
    textButtonLabel: {
      color: colors.accent,
      flexShrink: 1,
      fontSize: 16,
      fontWeight: '800',
      textAlign: 'center',
    },
    titleInput: {
      color: colors.textPrimary,
      fontSize: 30,
      fontWeight: '900',
      lineHeight: 36,
      paddingVertical: Spacing.one,
    },
  });
