import { StyleSheet } from 'react-native';

import { Colors, MaxContentWidth, Spacing } from '@/constants/theme';

export const createStyles = (colors: typeof Colors.light) =>
  StyleSheet.create({
    addWorkoutButton: {
      alignItems: 'center',
      backgroundColor: colors.surfaceSecondary,
      borderCurve: 'continuous',
      borderRadius: 18,
      marginTop: Spacing.two,
      minHeight: 48,
      justifyContent: 'center',
      paddingHorizontal: Spacing.three,
      paddingVertical: 14,
    },
    addWorkoutLabel: {
      color: colors.textPrimary,
      flexShrink: 1,
      fontSize: 15,
      fontWeight: '800',
      textAlign: 'center',
    },
    container: {
      maxWidth: MaxContentWidth,
      width: '100%',
    },
    content: {
      alignItems: 'center',
      flexGrow: 1,
      paddingHorizontal: Spacing.three,
      paddingTop: Spacing.three,
    },
    emptyContainer: {
      alignItems: 'center',
      gap: Spacing.two,
      paddingHorizontal: Spacing.three,
    },
    emptyState: {
      backgroundColor: colors.surfaceSecondary,
      borderCurve: 'continuous',
      borderRadius: 20,
      gap: 4,
      marginTop: Spacing.two,
      padding: Spacing.three,
    },
    emptyStateSubtitle: {
      color: colors.textSecondary,
      fontSize: 13,
      lineHeight: 18,
    },
    emptyStateTitle: {
      color: colors.textPrimary,
      fontSize: 15,
      fontWeight: '800',
    },
    emptyText: {
      color: colors.textSecondary,
      fontSize: 14,
      lineHeight: 20,
      textAlign: 'center',
    },
    emptyTitle: {
      color: colors.textPrimary,
      fontSize: 22,
      fontWeight: '900',
      textAlign: 'center',
    },
    fill: {
      flex: 1,
    },
    fieldGroup: {
      gap: Spacing.one,
    },
    fieldLabel: {
      color: colors.textSecondary,
      fontSize: 13,
      fontWeight: '700',
    },
    header: {
      alignItems: 'center',
      borderBottomWidth: StyleSheet.hairlineWidth,
      flexDirection: 'row',
      gap: Spacing.two,
      justifyContent: 'space-between',
      paddingBottom: Spacing.two,
      paddingHorizontal: Spacing.three,
    },
    headerAction: {
      alignItems: 'flex-start',
      flexShrink: 0,
      justifyContent: 'center',
      maxWidth: 100,
      minHeight: 44,
      minWidth: 56,
      paddingVertical: 8,
    },
    headerActionLabel: {
      color: colors.textSecondary,
      flexShrink: 1,
      fontSize: 15,
      fontWeight: '800',
    },
    headerTitle: {
      color: colors.textPrimary,
      flex: 1,
      flexShrink: 1,
      fontSize: 18,
      fontWeight: '900',
      minWidth: 0,
      textAlign: 'center',
    },
    input: {
      backgroundColor: colors.backgroundSecondary ?? colors.surfaceSecondary,
      borderColor: colors.borderSubtle,
      borderCurve: 'continuous',
      borderRadius: 16,
      borderWidth: StyleSheet.hairlineWidth,
      color: colors.textPrimary,
      fontSize: 16,
      minHeight: 50,
      paddingHorizontal: Spacing.three,
    },
    overflowButton: {
      alignItems: 'center',
      alignSelf: 'stretch',
      flexShrink: 0,
      justifyContent: 'center',
      minWidth: 44,
      paddingHorizontal: Spacing.one,
    },
    overflowLabel: {
      color: colors.textSecondary,
      fontSize: 22,
      fontWeight: '900',
      marginTop: -2,
    },
    pressed: {
      opacity: 0.72,
    },
    primaryButton: {
      alignItems: 'center',
      backgroundColor: colors.accent,
      borderCurve: 'continuous',
      borderRadius: 16,
      minHeight: 48,
      justifyContent: 'center',
      paddingHorizontal: Spacing.three,
      paddingVertical: 14,
    },
    primaryLabel: {
      color: colors.background,
      flexShrink: 1,
      fontSize: 15,
      fontWeight: '900',
      textAlign: 'center',
    },
    saveAction: {
      alignItems: 'flex-end',
      flexShrink: 0,
      justifyContent: 'center',
      maxWidth: 100,
      minHeight: 44,
      minWidth: 56,
      paddingVertical: 8,
    },
    saveActionDisabled: {
      opacity: 0.38,
    },
    saveActionLabel: {
      color: colors.accent,
      flexShrink: 1,
      fontSize: 15,
      fontWeight: '900',
      textAlign: 'right',
    },
    screen: {
      flex: 1,
    },
    scrollView: {
      flex: 1,
    },
    sectionHeaderRow: {
      alignItems: 'center',
      flexDirection: 'row',
      flexWrap: 'wrap',
      gap: Spacing.two,
      justifyContent: 'space-between',
      marginTop: Spacing.three,
    },
    sectionTitle: {
      color: colors.textPrimary,
      flexShrink: 1,
      fontSize: 18,
      fontWeight: '900',
      minWidth: 0,
    },
    startNextButton: {
      flexShrink: 1,
      minHeight: 44,
      justifyContent: 'center',
      paddingVertical: 6,
    },
    startNextLabel: {
      color: colors.accent,
      flexShrink: 1,
      fontSize: 13,
      fontWeight: '800',
      textAlign: 'right',
    },
    workoutList: {
      gap: Spacing.two,
      marginTop: Spacing.two,
    },
    workoutRow: {
      alignItems: 'center',
      backgroundColor: colors.surfaceSecondary,
      borderCurve: 'continuous',
      borderRadius: 20,
      flexDirection: 'row',
      gap: Spacing.one,
      paddingLeft: Spacing.three,
      paddingRight: Spacing.one,
      paddingVertical: 12,
    },
    workoutRowBody: {
      alignItems: 'center',
      flex: 1,
      flexDirection: 'row',
      gap: Spacing.two,
      minHeight: 44,
      minWidth: 0,
    },
    workoutRowChevron: {
      color: colors.textSecondary,
      flexShrink: 0,
      fontSize: 22,
      fontWeight: '900',
      marginLeft: 'auto',
      paddingHorizontal: Spacing.one,
    },
    workoutRowCopy: {
      flex: 1,
      gap: 4,
      minWidth: 0,
    },
    workoutRowMeta: {
      color: colors.textSecondary,
      flexShrink: 1,
      fontSize: 12,
      fontWeight: '700',
    },
    workoutRowTitle: {
      color: colors.textPrimary,
      flexShrink: 1,
      fontSize: 15,
      fontWeight: '800',
    },
  });
