export function getLabsCopy(locale: string) {
  const russian = locale.toLowerCase().startsWith('ru');

  return russian
    ? {
        tabTitle: 'Анализы',
        subtitle: 'Документы, показатели и динамика в одном месте.',
        emptyTitle: 'Добавьте первый анализ',
        emptyBody:
          'Здесь появятся подтверждённые показатели, история документов, отклонения и графики. Распознанные данные сохраняются только после вашей проверки.',
        addResults: 'Добавить результаты',
        uploadUnavailable:
          'Загрузка будет включена после подключения приватного хранилища и worker-пайплайна. Сейчас экран уже работает с server-authoritative документами.',
        documentsTitle: 'Документы',
        loading: 'Загружаем анализы…',
        loadFailed: 'Не удалось загрузить анализы.',
        retry: 'Повторить',
        biomarkersTitle: 'Показатели',
        biomarkersBody: 'Подтверждённые результаты формируют историю по каждому маркеру.',
        trendsTitle: 'Динамика',
        trendsBody: 'Графики используют только подтверждённые значения.',
        reviewTitle: 'Проверка результатов',
        reviewSubtitle:
          'Каждое распознанное значение нужно принять, исправить или исключить перед сохранением.',
        reviewLoading: 'Загружаем распознанные показатели…',
        reviewFailed: 'Не удалось загрузить данные для проверки.',
        accept: 'Принять',
        exclude: 'Исключить',
        edit: 'Исправить',
        cancel: 'Отмена',
        saveCorrection: 'Сохранить исправление',
        accepted: 'Принято',
        corrected: 'Исправлено',
        excluded: 'Исключено',
        needsReview: 'Нужно проверить',
        unresolved: 'Маркер или единица пока не распознаны надёжно',
        confidence: 'Уверенность распознавания',
        marker: 'Показатель',
        value: 'Значение',
        unit: 'Единица',
        referenceLow: 'Референс от',
        referenceHigh: 'Референс до',
        referenceUnit: 'Единица референса',
        collectionDate: 'Дата забора',
        collectionDateHint: 'ГГГГ-ММ-ДД',
        confirm: 'Сохранить подтверждённые результаты',
        confirmBlocked: 'Сначала проверьте все распознанные строки.',
        documentNotReady: 'Документ пока не готов к проверке.',
        status: {
          pending_upload: 'Загрузка не завершена',
          uploaded: 'Ожидает обработки',
          processing: 'Распознаём документ',
          review_required: 'Нужно проверить',
          confirmed: 'Подтверждено',
          failed: 'Ошибка обработки',
        },
      }
    : {
        tabTitle: 'Labs',
        subtitle: 'Documents, biomarkers, and trends in one place.',
        emptyTitle: 'Add your first lab result',
        emptyBody:
          'Confirmed biomarkers, documents, attention states, and trends will live here. Extracted values are saved only after you review them.',
        addResults: 'Add results',
        uploadUnavailable:
          'Upload will be enabled after private storage and the worker pipeline are connected. This screen already uses server-authoritative documents.',
        documentsTitle: 'Documents',
        loading: 'Loading lab documents…',
        loadFailed: 'Unable to load lab documents.',
        retry: 'Retry',
        biomarkersTitle: 'Biomarkers',
        biomarkersBody: 'Confirmed results build a longitudinal history for each marker.',
        trendsTitle: 'Trends',
        trendsBody: 'Charts use confirmed values only.',
        reviewTitle: 'Review results',
        reviewSubtitle:
          'Accept, correct, or exclude every extracted value before it becomes health history.',
        reviewLoading: 'Loading extracted results…',
        reviewFailed: 'Unable to load results for review.',
        accept: 'Accept',
        exclude: 'Exclude',
        edit: 'Correct',
        cancel: 'Cancel',
        saveCorrection: 'Save correction',
        accepted: 'Accepted',
        corrected: 'Corrected',
        excluded: 'Excluded',
        needsReview: 'Needs review',
        unresolved: 'Marker or unit is not safely normalized yet',
        confidence: 'Extraction confidence',
        marker: 'Biomarker',
        value: 'Value',
        unit: 'Unit',
        referenceLow: 'Reference low',
        referenceHigh: 'Reference high',
        referenceUnit: 'Reference unit',
        collectionDate: 'Collection date',
        collectionDateHint: 'YYYY-MM-DD',
        confirm: 'Save confirmed results',
        confirmBlocked: 'Review every extracted row first.',
        documentNotReady: 'This document is not ready for review yet.',
        status: {
          pending_upload: 'Upload incomplete',
          uploaded: 'Queued for processing',
          processing: 'Reading document',
          review_required: 'Needs review',
          confirmed: 'Confirmed',
          failed: 'Processing failed',
        },
      };
}
