export function getLabsCopy(locale: string) {
  const russian = locale.toLowerCase().startsWith('ru');

  return russian
    ? {
        tabTitle: 'Анализы',
        subtitle: 'Документы, показатели и динамика в одном месте.',
        emptyTitle: 'Добавьте первый анализ',
        emptyBody:
          'Здесь появятся подтверждённые показатели, история документов, отклонения и графики. Распознанные данные сохраняются только после вашей проверки.',
        addResults: 'Добавить результаты',
        addPhoto: 'Выбрать фото анализа',
        addPdf: 'Выбрать PDF анализа',
        uploadHint:
          'Фото или PDF загружается напрямую в приватное хранилище по временной signed-ссылке. В историю попадут только результаты, которые вы проверите и подтвердите.',
        uploadInProgress: 'Загружаем документ…',
        uploadFailed: 'Не удалось загрузить документ анализа.',
        unsupportedPhoto: 'Поддерживаются PDF, JPEG, PNG и HEIC до 25 МБ.',
        documentsTitle: 'Документы',
        noDocuments: 'Загруженных документов пока нет.',
        loading: 'Загружаем анализы…',
        loadFailed: 'Не удалось загрузить анализы.',
        retry: 'Повторить',
        attentionTitle: 'Требует внимания',
        biomarkersTitle: 'Показатели',
        biomarkersBody: 'Подтверждённые результаты формируют историю по каждому маркеру.',
        noBiomarkers: 'После подтверждения анализа здесь появятся показатели.',
        trendsTitle: 'Динамика',
        trendsBody: 'Графики используют только подтверждённые значения.',
        historyTitle: 'История',
        currentTitle: 'Текущее значение',
        referenceTitle: 'Референс лаборатории',
        noReference: 'Референс не указан в исходном анализе',
        noHistory: 'Для графика нужен хотя бы один подтверждённый результат.',
        reviewTitle: 'Проверка результатов',
        reviewSubtitle:
          'Каждое распознанное значение нужно принять, исправить или исключить перед сохранением.',
        reviewLoading: 'Загружаем распознанные показатели…',
        reviewFailed: 'Не удалось загрузить данные для проверки.',
        accept: 'Принять',
        exclude: 'Исключить',
        edit: 'Исправить',
        cancel: 'Отмена',
        saveCorrection: 'Сохранить исправление',
        accepted: 'Принято',
        corrected: 'Исправлено',
        excluded: 'Исключено',
        needsReview: 'Нужно проверить',
        unresolved: 'Маркер или единица пока не распознаны надёжно',
        confidence: 'Уверенность распознавания',
        marker: 'Показатель',
        value: 'Значение',
        unit: 'Единица',
        referenceLow: 'Референс от',
        referenceHigh: 'Референс до',
        referenceUnit: 'Единица референса',
        collectionDate: 'Дата забора',
        collectionDateHint: 'ГГГГ-ММ-ДД',
        confirm: 'Сохранить подтверждённые результаты',
        confirmBlocked: 'Сначала проверьте все распознанные строки.',
        documentNotReady: 'Документ пока не готов к проверке.',
        semanticState: {
          unknown: 'Нет достаточного референсного контекста',
          in_range: 'В референсном диапазоне',
          borderline: 'Около границы по настроенному правилу',
          out_of_range: 'Вне референсного диапазона',
          significantly_out_of_range: 'Значительно вне диапазона по настроенному правилу',
        },
        status: {
          pending_upload: 'Загрузка не завершена',
          uploaded: 'Ожидает обработки',
          processing: 'Распознаём документ',
          review_required: 'Нужно проверить',
          confirmed: 'Подтверждено',
          failed: 'Ошибка обработки',
        },
      }
    : {
        tabTitle: 'Labs',
        subtitle: 'Documents, biomarkers, and trends in one place.',
        emptyTitle: 'Add your first lab result',
        emptyBody:
          'Confirmed biomarkers, documents, attention states, and trends will live here. Extracted values are saved only after you review them.',
        addResults: 'Add results',
        addPhoto: 'Choose lab photo',
        addPdf: 'Choose lab PDF',
        uploadHint:
          'The photo or PDF uploads directly to private storage through a short-lived signed URL. Only results you review and confirm become health history.',
        uploadInProgress: 'Uploading document…',
        uploadFailed: 'Unable to upload the lab document.',
        unsupportedPhoto: 'PDF, JPEG, PNG, and HEIC up to 25 MB are supported.',
        documentsTitle: 'Documents',
        noDocuments: 'No uploaded documents yet.',
        loading: 'Loading lab documents…',
        loadFailed: 'Unable to load lab documents.',
        retry: 'Retry',
        attentionTitle: 'Needs attention',
        biomarkersTitle: 'Biomarkers',
        biomarkersBody: 'Confirmed results build a longitudinal history for each marker.',
        noBiomarkers: 'Biomarkers will appear after a lab document is confirmed.',
        trendsTitle: 'Trends',
        trendsBody: 'Charts use confirmed values only.',
        historyTitle: 'History',
        currentTitle: 'Current value',
        referenceTitle: 'Laboratory reference',
        noReference: 'No reference interval was supplied by the source lab',
        noHistory: 'At least one confirmed result is required for a chart.',
        reviewTitle: 'Review results',
        reviewSubtitle:
          'Accept, correct, or exclude every extracted value before it becomes health history.',
        reviewLoading: 'Loading extracted results…',
        reviewFailed: 'Unable to load results for review.',
        accept: 'Accept',
        exclude: 'Exclude',
        edit: 'Correct',
        cancel: 'Cancel',
        saveCorrection: 'Save correction',
        accepted: 'Accepted',
        corrected: 'Corrected',
        excluded: 'Excluded',
        needsReview: 'Needs review',
        unresolved: 'Marker or unit is not safely normalized yet',
        confidence: 'Extraction confidence',
        marker: 'Biomarker',
        value: 'Value',
        unit: 'Unit',
        referenceLow: 'Reference low',
        referenceHigh: 'Reference high',
        referenceUnit: 'Reference unit',
        collectionDate: 'Collection date',
        collectionDateHint: 'YYYY-MM-DD',
        confirm: 'Save confirmed results',
        confirmBlocked: 'Review every extracted row first.',
        documentNotReady: 'This document is not ready for review yet.',
        semanticState: {
          unknown: 'Reference context unavailable',
          in_range: 'Within laboratory reference range',
          borderline: 'Near a boundary under a configured rule',
          out_of_range: 'Outside laboratory reference range',
          significantly_out_of_range: 'Significantly outside range under a configured rule',
        },
        status: {
          pending_upload: 'Upload incomplete',
          uploaded: 'Queued for processing',
          processing: 'Reading document',
          review_required: 'Needs review',
          confirmed: 'Confirmed',
          failed: 'Processing failed',
        },
      };
}
